/* eslint-disable */
 function _optionalChain(ops) { let lastAccessLHS = undefined; let value = ops[0]; let i = 1; while (i < ops.length) { const op = ops[i]; const fn = ops[i + 1]; i += 2; if ((op === 'optionalAccess' || op === 'optionalCall') && value == null) { return undefined; } if (op === 'access' || op === 'optionalAccess') { lastAccessLHS = value; value = fn(value); } else if (op === 'call' || op === 'optionalCall') { value = fn((...args) => value.call(lastAccessLHS, ...args)); lastAccessLHS = undefined; } } return value; }import React, { useState } from 'react';
import { ChevronLeft, ChevronRight, Check, Download, HelpCircle, Eye, Edit3 } from 'lucide-react';

const MotivationWorkbook = () => {
  const [showIntro, setShowIntro] = useState(true);
  const [currentPhase, setCurrentPhase] = useState('round1');
  const [currentStep, setCurrentStep] = useState(0);
  const [selectedSteps, setSelectedSteps] = useState([]);
  const [showGuide, setShowGuide] = useState({});
  const [downloadSuccess, setDownloadSuccess] = useState(false);
  const [showRawAnswers, setShowRawAnswers] = useState(false);
  const [finalText, setFinalText] = useState('');
  const [basicInfo, setBasicInfo] = useState({ industry: '', position: '', company: '' });
  const [answers, setAnswers] = useState({});

  // ── 1라운드 ────────────────────────────────────────────────
  const round1Steps = [
    { id: 0, title: '기본 정보 입력', subtitle: '지원할 산업, 직무, 회사를 입력하세요' },
    { id: 1, title: 'Q1: 왜 이 직무인가', subtitle: '단순 관심을 넘어 가치관·비전·인생 목표와 이 직무의 연결',
      questions: [
        { id: 'q1_1', label: 'Q1-1. 이 직무에 관심을 갖게 된 구체적인 계기는 무엇인가요?', hint: '언제, 어디서, 무엇을 통해 — 특정 장면과 감정이 있어야 합니다', guide: { description: '막연한 관심이 아닌 특정 사건·장면·감정으로 표현하세요.', diagnosis: '즉석자가진단: "그때 어떤 기분이었나요?"라고 물으면 즉답 가능한가?', helpQuestions: ['정확히 언제였나요? (학년, 학기, 년도)', '어떤 상황에서였나요?', '그때 어떤 감정을 느꼈나요?'], ifDifficult: '이 직무를 알게 된 첫 순간을 떠올려보세요. 관련 수업, 책, 영상, 사람을 만난 순간을 생각해보세요.', ifStillDifficult: '주변 사람 중 이 일을 하는 사람을 만난 경험이나, 관련 기사를 읽은 경험을 떠올려보세요.' }, placeholder: '예: 대학교 2학년 마케팅원론 수업에서 실제 스타트업과 협업해 캠페인을 기획했을 때, 데이터로 고객의 숨은 니즈를 발견하고 이것이 300% 매출 상승으로 이어지는 것을 보며 처음으로 "이 일을 계속하고 싶다"는 확신이 생겼습니다.', rows: 4 },
        { id: 'q1_2', label: 'Q1-2. 이 직무가 나의 가치관·비전·인생 목표와 어떻게 연결되나요?', hint: '"잘 맞는다" 수준을 넘어 이 직무가 자신의 삶에서 어떤 의미인지까지', guide: { description: '이 직무가 왜 하필 나여야 하는지, 삶의 방향과 어떻게 연결되는지가 핵심입니다.', diagnosis: '즉석자가진단: "왜 하필 이 직무인가요?"라고 물으면 가치관과 연결해 즉답 가능한가?', helpQuestions: ['내가 중요하게 생각하는 가치는 무엇인가요?', '이 직무가 그 가치와 어떻게 맞닿나요?', '이 직무 없이도 그 가치를 실현할 수 있나요?'], ifDifficult: '이 직무를 하면서 느끼는 보람이 나의 어떤 성향과 연결되는지 생각해보세요.', ifStillDifficult: '다른 직무를 했을 때를 상상해보세요. 무엇이 아쉬울 것 같나요?' }, placeholder: '예: "왜 사람들은 이것을 선택하는가"를 데이터와 창의력으로 풀어내는 일을 평생 업으로 삼고 싶다는 확신이 이 직무를 선택한 나만의 이유입니다.', rows: 4 },
        { id: 'q1_3', label: 'Q1-3. 이 직무에서 성장하면 어떤 일을 하게 되는지 알고 있나요? 그 모습 중 해보고 싶은 것은?', hint: '리서치 기반 — 현직자 인터뷰, 시니어 채용공고 등을 참고하세요', guide: { description: '이 직무의 성장 경로를 이해하고 있다는 것 자체가 강력한 지원 이유가 됩니다.', diagnosis: '즉석자가진단: "3년 후에 어떤 일을 하고 싶어요?"라고 물으면 리서치 기반으로 즉답 가능한가?', helpQuestions: ['시니어 채용공고에서 신입 공고에 없는 항목은?', '현직자 인터뷰에서 "경험이 쌓이면 하게 되는 일"은?', '그 중 해보고 싶은 것과 그 이유는?'], ifDifficult: '시니어 JD와 신입 JD를 나란히 놓고 비교해보세요.', ifStillDifficult: '현직자 인터뷰 영상 3편 이상을 보고 공통 성장 경험을 정리해보세요.' }, placeholder: '예: 시니어 마케터는 캠페인 전략 총괄, 브랜드 포지셔닝 설계를 합니다. 저는 특히 데이터와 크리에이티브를 결합해 브랜드 전략을 설계하는 역할에 도달하고 싶습니다.', rows: 4 }
      ] },
    { id: 2, title: 'Q2: 왜 이 회사인가', subtitle: '같은 직무를 하는 수많은 회사 중 이 회사여야 하는 이유',
      questions: [
        { id: 'q2_1', label: 'Q2-1. 이 회사만의 차별점은 무엇인가요?', hint: '리서치 없이는 쓸 수 없는 구체적 사실 — "좋은 회사라서"는 답이 아닙니다', guide: { description: '"업계 1위", "성장 가능성"은 누구나 씁니다. 다른 회사에 해당 안 되는 사실이어야 합니다.', diagnosis: '즉석자가진단: "다른 회사도 좋은데 왜 여기인가요?"에 명확히 답변 가능한가?', helpQuestions: ['이 회사의 독특한 비즈니스 모델이나 전략은?', '조직 문화나 업무 방식의 특징은?', '최근 1년 이내 주목할 뉴스나 프로젝트는?'], ifDifficult: '회사 홈페이지 뉴스룸, CEO 인터뷰, 보도자료를 확인하세요.', ifStillDifficult: '경쟁사 2곳과 비교해보세요. 비교하면 차별점이 보입니다.' }, placeholder: '예: 귀사는 자체 데이터 플랫폼을 보유해 1st party data 기반 마케팅이 가능합니다. 대부분의 경쟁사가 외부 데이터에 의존하는 반면...', rows: 4 },
        { id: 'q2_2', label: 'Q2-2. 이 회사의 특징이 나의 가치관·비전과 어떻게 연결되나요?', hint: 'Q1의 가치관과 이 회사의 특징이 직접 연결되어야 합니다', guide: { description: '다른 회사가 아닌 이 회사여야 하는 개인적이고 구체적인 이유를 찾으세요.', diagnosis: '즉석자가진단: "구체적인 연결 지점을 하나만 말해주세요"에 즉답 가능한가?', helpQuestions: ['Q1에서 말한 가치관이 이 회사에서 어떻게 실현되나요?', '이 회사의 방향성이 나의 성장 방향과 맞는 이유는?', '경쟁사가 아닌 이 회사를 선택한 결정적 이유 하나는?'], ifDifficult: '자신의 가치관을 먼저 정리한 후 회사 특징과의 교집합을 찾아보세요.', ifStillDifficult: '이 회사에서 일하는 자신을 상상해보세요. 다른 회사에서는 느낄 수 없는 것은?' }, placeholder: '예: "데이터로 고객의 선택을 이해하고 싶다"는 제 목표는 귀사의 1st party data 환경에서 가장 직접적으로 실현될 수 있습니다.', rows: 4 }
      ] },
    { id: 3, title: 'Q3: 무엇을 왜 준비했는가', subtitle: '동기를 위해 준비한 역량과 그 목적 — 방향성 있는 준비의 증거',
      questions: [
        { id: 'q3_1', label: 'Q3-1. 이 직무에 필요하다고 판단한 역량은 무엇이고, 왜 그렇게 판단했나요?', hint: '"~하기 위해 ~이 필요하다고 판단했다" — 목적이 드러나야 합니다', guide: { description: '역량 나열이 아닌 왜 그 역량이 필요한지 이유가 있어야 합니다.', diagnosis: '즉석자가진단: "왜 그 역량을 준비했나요?"에 직무와 연결해 즉답 가능한가?', helpQuestions: ['채용공고에서 강조하는 역량은?', '현직자가 "이게 없으면 힘들다"고 한 것은?', '그 역량이 없으면 어떤 문제가 생기나요?'], ifDifficult: 'Q1-3 성장 경로에서 필요 역량을 역산해보세요.', ifStillDifficult: '채용공고 자격요건과 우대사항을 분리해 각각 왜 필요한지 써보세요.' }, placeholder: '예: 고객 행동 데이터를 직접 다루려면 SQL이 필수이고, 캠페인 성과를 측정하려면 GA가 필요하다고 판단했습니다.', rows: 4 },
        { id: 'q3_2', label: 'Q3-2. 그 역량을 위해 어떤 준비를 했나요?', hint: '"그냥 했다"가 아닌, 이 직무를 향한 방향성 있는 선택이어야 합니다', guide: { description: '스펙 쌓기가 아닌 "하고 싶은 일을 위해 의도적으로 준비한 것"이어야 합니다.', diagnosis: '즉석자가진단: 각 활동의 이유가 이 직무를 향한 동기와 연결되나요?', helpQuestions: ['각 활동을 시작한 직접적인 계기는?', '기대한 것과 실제로 얻은 것은?', '이 활동이 없었다면 나는 어떻게 달랐을까?'], ifDifficult: '이유 없는 활동은 과감하게 빼세요. 이유 있는 것만 남기세요.', ifStillDifficult: '가장 의미 있었던 활동 하나를 STAR 방식으로 깊게 써보세요.' }, placeholder: '예: SQL 강의 → 고객 데이터 직접 추출 필요. GA 자격증 → 웹 행동 데이터 체계적 학습. SNS 프로젝트 → A/B 테스트 직접 설계 경험.', rows: 4 },
        { id: 'q3_3', label: 'Q3-3. 준비한 역량이 이 회사의 어떤 업무에서 어떻게 쓰일 수 있나요?', hint: '역량과 직무 업무를 1:1로 연결하는 연습', guide: { description: '이 연결이 없으면 Q4(기여)를 쓸 수 없습니다. 채용공고 주요 업무를 열어두고 작성하세요.', diagnosis: '즉석자가진단: "이 역량이 없었다면 이 업무를 할 수 없었을까요?"에 "예"라고 답할 수 있나요?', helpQuestions: ['채용공고의 주요 업무 목록을 확인했나요?', '내 역량 중 그 업무에 직접 연결되는 것은?', '연결이 안 되는 역량은 굳이 언급 불필요'], ifDifficult: '"이 역량이 있어서 이 업무의 이 부분을 할 수 있다"로 써보세요.', ifStillDifficult: '채용공고 주요 업무 3가지를 적고, 각각에 연결되는 내 역량을 옆에 쓰세요.' }, placeholder: '예: SQL → "고객 행동 데이터 분석" 업무. GA → "채널별 퍼포먼스 측정" 업무. A/B 테스트 → "마케팅 실험 설계" 업무.', rows: 4 }
      ] },
    { id: 4, title: 'Q4: 어떻게 기여할 수 있는가', subtitle: 'Q1~Q3의 자연스러운 결론 — 동기와 준비가 기여로 이어지는 논리',
      questions: [
        { id: 'q4_1', label: 'Q4-1. 동기와 역량이 이 회사에서 어떻게 기여로 이어지나요?', hint: '"열심히 하겠습니다"가 아닌 동기+역량의 인과적 결론', guide: { description: '"[동기] 때문에 [역량]을 준비했고, 그래서 [기여]가 가능하다"의 구조입니다.', diagnosis: '즉석자가진단: "그래서 왜요?"라고 물으면 Q1~Q3을 근거로 막히지 않나요?', helpQuestions: ['Q1에서 쓴 동기 (핵심 한 문장)는?', 'Q3에서 쓴 역량 (가장 연결되는 것)은?', '이 역량이 어떤 업무에서 어떻게 쓰이나요?'], ifDifficult: '"~기 때문에 ~을 준비했고, 따라서 ~할 수 있다"로 연결해보세요.', ifStillDifficult: '동기·역량·기여를 각각 한 문장으로 쓴 뒤 이어 붙여보세요.' }, placeholder: '예: 데이터로 고객의 선택을 이해하고 싶다는 동기가 있었기 때문에 SQL과 GA를 익혔고, 귀사의 고객 행동 데이터 분석 업무에 즉시 기여할 수 있습니다.', rows: 4 },
        { id: 'q4_2', label: 'Q4-2. 이 회사가 지금 집중하는 과제와 내 기여가 어떻게 연결되나요?', hint: 'Q2 리서치 결과와 Q3 역량을 연결 — 추상이 아닌 구체적인 지점', guide: { description: '"이 회사의 이 과제에 내 역량이 이렇게 연결된다"가 보이면 기여 논리가 완성됩니다.', diagnosis: '즉석자가진단: "다른 회사에서도 이 기여가 가능했을까요?"에 "아니요"가 나와야 합니다.', helpQuestions: ['Q2에서 파악한 이 회사의 과제를 하나 적으세요', '그 과제에 필요한 역량은?', '내 역량과 어떻게 겹치나요?'], ifDifficult: '"이 회사가 이 과제를 해결하는 과정에서 내 역할은?"이라고 자문해보세요.', ifStillDifficult: '최근 뉴스 하나를 골라 내 역량과의 접점을 찾아보세요.' }, placeholder: '예: 귀사의 개인화 추천 시스템 고도화 과정에서 고객 행동 세그먼트를 정교화하는 데이터 분석으로 직접 기여할 수 있습니다.', rows: 4 }
      ] }
  ];

  // ── 2라운드 심화 ───────────────────────────────────────────
  const round2Questions = {
    1: [
      { id: 'q2_1_1', label: 'Q1 심화-1. 현직자 인터뷰 3편 이상에서 공통적으로 강조하는 것은?', hint: '리서치 없이는 쓸 수 없는 내용이어야 합니다', guide: { description: '현직자들이 공통적으로 말하는 것이 채용공고에 없는 진짜 핵심입니다.', diagnosis: '즉석자가진단: 현직자 3명이 공통으로 언급한 역량을 하나 이상 찾았나요?', helpQuestions: ['"[직무명] 현직자 인터뷰"로 검색', '"이게 없으면 힘들더라"고 한 것은?', '"처음엔 몰랐는데 꼭 필요하더라"는?'], ifDifficult: '리서치에 30분만 투자하면 채용공고에서 못 찾는 인사이트를 얻습니다.', ifStillDifficult: '블라인드나 잡플래닛에서 해당 직무 관련 내용을 찾아보세요.' }, placeholder: '예: 현직 마케터 5편을 보니 공통적으로 "데이터 해석보다 타겟 언어 변환 능력이 더 중요하다"고 했습니다.', rows: 4 },
      { id: 'q2_1_2', label: 'Q1 심화-2. 비슷한 다른 직무 2개와 비교했을 때, 왜 하필 이 직무인가요?', hint: '비교를 통해 "이 직무에서만 중요한 이유"가 드러납니다', guide: { description: '비슷한 직무와 비교하면 "왜 하필 이 직무"인지가 명확해집니다.', diagnosis: '즉석자가진단: "다른 직무에서도 하지 않나요?"에 즉답 가능한가?', helpQuestions: ['비슷한 직무 2개의 핵심 역량을 비교', '이 직무에서만 특별히 중요한 이유는?', '이 역량 없이 대체 가능한가요?'], ifDifficult: '각 직무 채용공고를 나란히 놓고 비교하세요.', ifStillDifficult: '"이 직무에서 유독 중요한 상황"을 하나 떠올려보세요.' }, placeholder: '예: 기획은 구조 설계, 영업은 관계 구축이 핵심. 마케팅은 "고객 데이터에서 행동 패턴을 읽고 메시지로 전환"이 핵심인데, 이것이 제 가치관과 가장 맞닿습니다.', rows: 4 },
      { id: 'q2_1_3', label: 'Q1 심화-3. 이 직무가 없었다면 이 가치를 어떻게 실현했을까요?', hint: '이 직무가 대체 불가능한 이유를 보여주는 질문', guide: { description: '"다른 방법으로도 가능하다"면 이 직무를 선택한 이유가 약해집니다.', diagnosis: '즉석자가진단: "다른 직무에서도 가능하지 않나요?"에 즉답 가능한가?', helpQuestions: ['다른 방법으로 같은 가치를 실현할 수 있나요?', '그래도 이 직무를 선택한 이유는?', '이 직무만이 줄 수 있는 고유한 경험은?'], ifDifficult: '이 직무를 하는 순간이 가장 몰입되는 이유를 떠올려보세요.', ifStillDifficult: '이 직무를 평생 해야 한다면 기꺼이 할 수 있나요? 그 이유가 핵심입니다.' }, placeholder: '예: 컨설팅에서도 고객 분석을 하지만 "실행"까지 갈 수 없습니다. "설계부터 실행까지 일관된 과정"은 마케팅에서만 가능합니다.', rows: 4 }
    ],
    2: [
      { id: 'q2_2_1', label: 'Q2 심화-1. 경쟁사 2곳과 비교했을 때 장단점은? 그래도 선택한 이유는?', hint: '객관적 비교를 통해 선택 이유를 강화', guide: { description: '비교를 통해 "왜 하필 이 회사"인지 더 명확해집니다.', diagnosis: '즉석자가진단: "경쟁사도 좋은데 왜 여기?"에 명확히 답변 가능한가?', helpQuestions: ['경쟁사 A, B의 각각 강점은?', '이 회사의 단점은?', '그럼에도 선택한 결정적 이유는?'], ifDifficult: '시장점유율, 문화, 성장 기회 등으로 비교하세요.', ifStillDifficult: '"큰 회사에서 보조" vs "작은 회사에서 직접" 같은 구조적 차이를 찾으세요.' }, placeholder: '예: A사는 규모 크지만 신입은 보조 역할만. 이 회사는 신입부터 실제 데이터와 실험 참여 가능. "직접 설계하고 실행하는 것"이 내 성장에 더 맞습니다.', rows: 4 },
      { id: 'q2_2_2', label: 'Q2 심화-2. 이 회사가 직면한 도전 과제는? 거기에 내가 어떻게 연결되나요?', hint: '회사의 현재 과제를 파악하고 내 역량과 연결 — Q4 기여 논리의 토대', guide: { description: '도전 과제를 파악하고 있다는 것은 진지하게 리서치했다는 증거입니다.', diagnosis: '즉석자가진단: "이 회사가 지금 가장 어려운 부분은?"에 구체적으로 답할 수 있는가?', helpQuestions: ['업계 트렌드에서 이 회사가 대응해야 할 변화는?', 'CEO 인터뷰에서 강조한 방향은?', '그 과제 중 내 역량과 맞닿는 것은?'], ifDifficult: '회사 홈페이지 뉴스룸에서 최근 6개월 기사를 훑어보세요.', ifStillDifficult: '업계 전체 트렌드와 이 회사를 연결해도 좋습니다.' }, placeholder: '예: [도전 과제] MZ세대 고객 확보 + 데이터 마케팅 고도화. [연결] MZ세대인 저는 또래 소비 심리를 데이터로 검증하는 시각이 있고, SQL·GA 역량이 이 방향과 일치합니다.', rows: 4 }
    ],
    3: [
      { id: 'q2_3_1', label: 'Q3 심화-1. 활동을 모두 나열하고 각각 "왜 했는지" 한 줄씩 써보세요.', hint: '"그냥 했다", "스펙 때문에"는 답이 아닙니다', guide: { description: '활동마다 진짜 이유를 찾는 것이 Q3의 핵심입니다.', diagnosis: '즉석자가진단: 각 활동 이유가 직무 동기와 연결되나요?', helpQuestions: ['시작 계기가 무엇이었나요?', '기대한 것은? 실제 얻은 것은?', '이유 없는 활동은 과감히 빼세요'], ifDifficult: '이유 있는 활동만 남기고 직무 연결 3개로 줄여보세요.', ifStillDifficult: '"이 활동이 없었다면 나는 어떻게 달랐을까?"로 역추적하세요.' }, placeholder: '예: SQL → 고객 데이터 직접 추출 필요. GA 자격증 → 체계적 학습. 마케팅 동아리 → 실제 캠페인 경험. 토익(삭제) → 직무 연관 없음.', rows: 4 },
      { id: 'q2_3_2', label: 'Q3 심화-2. 가장 의미 있었던 활동 하나를 STAR 방식으로 써보세요.', hint: '하나를 깊게 쓰는 것 > 여러 개를 얕게 나열', guide: { description: 'S(상황) → T(과제) → A(행동) → R(결과) + 배운 것으로 깊게 쓰세요.', diagnosis: '즉석자가진단: "그 경험에서 배운 것이 이 직무와 어떻게 연결?"에 즉답 가능?', helpQuestions: ['S: 언제, 어디서?', 'T: 맡은 역할/문제는?', 'A: 구체적으로 무엇을 어떻게?', 'R: 숫자 결과는?'], ifDifficult: '숫자 없어도 "어떤 변화가 있었는지" 구체적으로 쓸 수 있습니다.', ifStillDifficult: '배운 것이 직무 선택 이유와 어떻게 연결되는지까지 써보세요.' }, placeholder: '예: S: SNS 프로젝트 콘텐츠 기획. T: 3개월 팔로워 1,000명. A: 매주 A/B 테스트. R: 클릭률 1.8배, 팔로워 1,200명. 배운 것: 감이 아닌 데이터로 개선 가능.', rows: 5 },
      { id: 'q2_3_3', label: 'Q3 심화-3. 현재 준비 상태를 솔직하게 평가하세요. 갖춘 것과 부족한 것은?', hint: '부족한 부분을 인정하는 것이 오히려 진정성을 높입니다', guide: { description: '갖춘 것과 부족한 것을 명확히 구분하고 보완 계획을 함께 제시하세요.', diagnosis: '즉석자가진단: "부족한 역량을 어떻게 채울 건가요?"에 구체적 계획 즉답?', helpQuestions: ['증거 있는 역량만 "갖췄다"고 쓰세요', '부족한 역량의 보완 계획은?', '이미 시작한 것이 있나요?'], ifDifficult: '역량 목록을 "충분/기초/부족"으로 분류해보세요.', ifStillDifficult: '"열심히 배우겠습니다"는 계획이 아닙니다. 구체적 방법+기간이 필요합니다.' }, placeholder: '예: ✅ SQL 기초, GA 자격증. ⚠️ Python 기초 수준. ❌ 유료 광고 집행 경험 없음. [보완] Python: 강의 수강 중. 유료 광고: 입사 전 소액 집행 예정.', rows: 5 }
    ],
    4: [
      { id: 'q2_4_1', label: 'Q4 심화-1. Q1(동기) → Q3(역량) → Q4(기여)를 한 문장으로 연결해보세요.', hint: '"[동기] 때문에 [역량]을 준비했고, 그래서 [기여]가 가능하다"', guide: { description: '이 세 가지가 인과관계로 연결될 때 Q4가 완성됩니다.', diagnosis: '즉석자가진단: 연결 문장 후 "그래서 왜요?"에 막히지 않나요?', helpQuestions: ['Q1 동기 (핵심 한 문장):', 'Q3 역량 (가장 연결되는 것):', '이 역량이 어떤 업무에서 어떻게?'], ifDifficult: '"~기 때문에 ~을 준비했고, 따라서 ~할 수 있다"로 연결.', ifStillDifficult: '동기·역량·기여를 각 한 문장으로 쓴 뒤 이어 붙이세요.' }, placeholder: '예: "데이터로 고객의 선택을 이해하고 싶다" → SQL+GA 학습 → 귀사의 고객 행동 데이터 분석 업무에 즉시 기여 가능.', rows: 5 },
      { id: 'q2_4_2', label: 'Q4 심화-2. 이 회사가 집중하는 과제 하나를 골라 내 기여를 연결해보세요.', hint: 'Q2 리서치와 Q3 역량을 연결 — 구체적인 지점', guide: { description: '"이 과제에 내 역량이 이렇게 연결"이 보이면 기여 논리 완성입니다.', diagnosis: '즉석자가진단: "다른 회사에서도 가능했을까요?"에 "아니요"가 나와야 합니다.', helpQuestions: ['Q2에서 파악한 과제 하나를 적으세요', '그 과제에 필요한 역량은?', '내 역량과 어떻게 겹치나요?'], ifDifficult: '최근 뉴스 하나를 골라 내 역량과의 접점을 찾아보세요.', ifStillDifficult: '"이 회사에서 이 역량이 특히 필요한 이유" 하나만 찾아도 됩니다.' }, placeholder: '예: [과제] AI 개인화 추천 고도화. [역량] SQL+GA. → "귀사의 개인화 추천 고도화에서 고객 세그먼트를 정교화하는 분석으로 기여할 수 있습니다."', rows: 5 }
    ]
  };

  // ── 3라운드 연결 ───────────────────────────────────────────
  const round3Questions = [
    { id: 'connect_q1q2', label: '연결 Q1→Q2: 왜 이 직무 → 왜 이 회사', hint: '"이 직무를 할 수 있는 곳은 많지만, 귀사를 선택한 이유는..."', placeholder: '예: 데이터로 고객의 선택을 설계하고 싶다는 확신이 생긴 이후, 이 일을 가장 잘 할 수 있는 환경을 찾았습니다. 귀사는 1st party data 기반 마케팅이 가능한 몇 안 되는 회사이고, 신입부터 실제 데이터와 실험에 참여할 수 있는 환경이 저의 성장 방향과 가장 맞닿아 있습니다.', rows: 5, referenceQuestions: ['q1_1', 'q1_2', 'q2_1', 'q2_2'] },
    { id: 'connect_q2q3', label: '연결 Q2→Q3: 왜 이 회사 → 무엇을 준비했는가', hint: '"그 확신이 생긴 이후부터 본격적으로 준비를 시작했습니다..."', placeholder: '예: 귀사에서 데이터 기반 마케팅을 하기 위해 고객 행동 데이터를 직접 다루는 역량이 필수라고 판단했습니다. SQL로 데이터를 직접 추출하고, GA로 웹 행동 데이터를 분석하고, SNS 프로젝트에서 A/B 테스트를 직접 설계하며 "감이 아닌 근거"로 마케팅하는 경험을 쌓았습니다.', rows: 5, referenceQuestions: ['q2_1', 'q2_2', 'q3_1', 'q3_2'] },
    { id: 'connect_q3q4', label: '연결 Q3→Q4: 준비한 역량 → 기여의 결론', hint: '"이렇게 준비해온 역량이 귀사에서 이런 방식으로..."', placeholder: '예: 이렇게 쌓아온 데이터 분석 역량은 귀사의 "고객 행동 데이터 분석" 업무에 즉시 활용됩니다. 개인화 추천 시스템 고도화라는 과제에서 고객 세그먼트를 정교화하는 분석으로 직접 기여할 수 있다고 생각하기 때문에 지원했습니다.', rows: 5, referenceQuestions: ['q3_2', 'q3_3', 'q4_1', 'q4_2'] }
  ];

  // ── 핸들러 ─────────────────────────────────────────────────
  const handleAnswerChange = (qid, val) => setAnswers(p => ({ ...p, [qid]: val }));
  const handleBasicInfoChange = (f, v) => setBasicInfo(p => ({ ...p, [f]: v }));
  const toggleGuide = (qid) => setShowGuide(p => ({ ...p, [qid]: !p[qid] }));
  const toggleStepSelection = (sid) => setSelectedSteps(p => p.includes(sid) ? p.filter(i => i !== sid) : [...p, sid]);

  const goToNextStep = () => {
    if (currentPhase === 'round1') { if (currentStep < round1Steps.length - 1) setCurrentStep(s => s + 1); else setCurrentPhase('evaluation'); }
    else if (currentPhase === 'evaluation') { setSelectedSteps(p => [...p].sort((a, b) => a - b)); setCurrentPhase('round2'); setCurrentStep(0); }
    else if (currentPhase === 'round2') { if (currentStep < selectedSteps.length - 1) setCurrentStep(s => s + 1); else { setCurrentPhase('round3'); setCurrentStep(0); } }
    else if (currentPhase === 'round3') { if (currentStep < round3Questions.length - 1) setCurrentStep(s => s + 1); else { setFinalText(genLetter()); setCurrentPhase('completed'); } }
  };
  const goToPrevStep = () => {
    if (currentPhase === 'completed') { setCurrentPhase('round3'); setCurrentStep(round3Questions.length - 1); }
    else if (currentStep > 0) setCurrentStep(s => s - 1);
    else if (currentPhase === 'round3') { setCurrentPhase('round2'); setCurrentStep(selectedSteps.length - 1); }
    else if (currentPhase === 'round2') setCurrentPhase('evaluation');
    else if (currentPhase === 'evaluation') { setCurrentPhase('round1'); setCurrentStep(round1Steps.length - 1); }
    else if (currentPhase === 'round1' && currentStep === 0) setShowIntro(true);
  };

  const genLetter = () => {
    const p = [];
    if (answers.connect_q1q2) p.push(answers.connect_q1q2); else { if (answers.q1_1) p.push(answers.q1_1); if (answers.q1_2) p.push(answers.q1_2); if (answers.q2_1) p.push('\n' + answers.q2_1); }
    if (answers.connect_q2q3) p.push('\n' + answers.connect_q2q3); else { if (answers.q3_1) p.push('\n' + answers.q3_1); if (answers.q3_2) p.push(answers.q3_2); }
    if (answers.connect_q3q4) p.push('\n' + answers.connect_q3q4); else { if (answers.q4_1) p.push('\n' + answers.q4_1); if (answers.q4_2) p.push(answers.q4_2); }
    return p.join('\n\n');
  };

  const downloadFinalText = () => {
    const h = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>지원동기</title><style>body{font-family:'맑은 고딕',sans-serif;line-height:1.8;padding:40px}p{margin-bottom:1em}</style></head><body>${finalText.split('\n\n').map(x => `<p>${x.replace(/\n/g,'<br>')}</p>`).join('\n')}</body></html>`;
    const b = new Blob([h], { type: 'application/msword;charset=utf-8' }); const u = URL.createObjectURL(b);
    const a = document.createElement('a'); a.href = u; a.download = `${basicInfo.company || '회사'}_지원동기.doc`; a.click();
    URL.revokeObjectURL(u); setDownloadSuccess(true); setTimeout(() => setDownloadSuccess(false), 5000);
  };

  const getRawText = () => `📋 원본 답변 모음\n\n[기본 정보]\n산업: ${basicInfo.industry||'-'}\n직무: ${basicInfo.position||'-'}\n회사: ${basicInfo.company||'-'}\n\n[Q1: 왜 이 직무인가]\nQ1-1 관심 계기: ${answers.q1_1||'-'}\nQ1-2 가치관 연결: ${answers.q1_2||'-'}\nQ1-3 성장 경로: ${answers.q1_3||'-'}\n\n[Q2: 왜 이 회사인가]\nQ2-1 차별점: ${answers.q2_1||'-'}\nQ2-2 가치관+회사: ${answers.q2_2||'-'}\n\n[Q3: 무엇을 왜 준비]\nQ3-1 필요 역량: ${answers.q3_1||'-'}\nQ3-2 준비 과정: ${answers.q3_2||'-'}\nQ3-3 업무 연결: ${answers.q3_3||'-'}\n\n[Q4: 어떻게 기여]\nQ4-1 동기→역량→기여: ${answers.q4_1||'-'}\nQ4-2 회사 과제 연결: ${answers.q4_2||'-'}\n\n[3라운드 연결]\nQ1→Q2: ${answers.connect_q1q2||'-'}\nQ2→Q3: ${answers.connect_q2q3||'-'}\nQ3→Q4: ${answers.connect_q3q4||'-'}`;

  const canGoNext = () => { if (currentPhase === 'evaluation') return selectedSteps.length >= 1; if (currentStep === 0 && currentPhase === 'round1') return !!(basicInfo.industry && basicInfo.position && basicInfo.company); return true; };
  const progress = currentPhase === 'round1' ? ((currentStep + 1) / round1Steps.length) * 33 : currentPhase === 'round2' ? 33 + ((currentStep + 1) / Math.max(selectedSteps.length, 1)) * 33 : 66 + ((currentStep + 1) / round3Questions.length) * 34;

  // ── 인트로 ─────────────────────────────────────────────────
  if (showIntro) return (React.createElement('div', { className: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-8"    ,}, React.createElement('div', { className: "max-w-4xl mx-auto" ,}, React.createElement('div', { className: "bg-white rounded-lg shadow-2xl p-8"   ,}
    , React.createElement('h1', { className: "text-4xl font-bold text-gray-800 mb-4 text-center"    ,}, "질문에 답하며 완성하는"  , React.createElement('br', null ), "지원동기 워크북" )
    , React.createElement('p', { className: "text-center text-gray-600 mb-8"  ,}, "CareerEngineer의 3라운드 체계적 작성 시스템"    )
    , React.createElement('div', { className: "bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-6 mb-8"     ,}, React.createElement('h2', { className: "text-2xl font-bold text-gray-800 mb-4"   ,}, "3라운드 작성 시스템"  ), React.createElement('div', { className: "space-y-4",}
      , React.createElement('div', { className: "bg-white rounded-lg p-4 border-l-4 border-blue-500"    ,}, React.createElement('h3', { className: "font-bold text-gray-800 mb-2"  ,}, "1라운드: 기본 지원동기 수립"   ), React.createElement('p', { className: "text-sm text-gray-700" ,}, "4개 Q 핵심 질문 — 왜 이 직무 · 왜 이 회사 · 무엇을 준비 · 어떻게 기여"                 ))
      , React.createElement('div', { className: "bg-white rounded-lg p-4 border-l-4 border-indigo-500"    ,}, React.createElement('h3', { className: "font-bold text-gray-800 mb-2"  ,}, "2라운드: 약한 부분 보강"   ), React.createElement('p', { className: "text-sm text-gray-700" ,}, "부족한 Q 선택 → 심화 질문으로 구체화 (1개 이상)"        ))
      , React.createElement('div', { className: "bg-white rounded-lg p-4 border-l-4 border-purple-500"    ,}, React.createElement('h3', { className: "font-bold text-gray-800 mb-2"  ,}, "3라운드: 연결 및 완성"   ), React.createElement('p', { className: "text-sm text-gray-700" ,}, "Q 간 연결 질문으로 자연스러운 인과 흐름 만들기"       ))
    ))
    , React.createElement('div', { className: "bg-yellow-50 border-l-4 border-yellow-400 p-6 mb-8"    ,}, React.createElement('h3', { className: "font-bold text-gray-800 mb-3"  ,}, "핵심 원칙" ), React.createElement('ul', { className: "space-y-2 text-sm text-gray-700"  ,}, React.createElement('li', null, React.createElement('strong', null, "진정성:"), " 3초 자가진단 통과한 내용만"    ), React.createElement('li', null, React.createElement('strong', null, "구체성:"), " 숫자, 날짜, 고유명사로 표현"    ), React.createElement('li', null, React.createElement('strong', null, "검증 가능성:" ), " 가족도 인정할 사실만"   )), React.createElement('div', { className: "mt-4 pt-4 border-t border-yellow-300"   ,}, React.createElement('p', { className: "text-sm font-semibold text-gray-800 mb-2"   ,}, "💡 3초 자가진단이란?"  ), React.createElement('p', { className: "text-sm text-gray-700" ,}, "\"정말이에요?\"라고 물었을 때 "   , React.createElement('strong', null, "3초 안에 구체적 예시나 증거를 댈 수 있는지"       ), " 확인하는 것입니다."  )))
    , React.createElement('div', { className: "bg-red-50 border-2 border-red-300 rounded-lg p-6 mb-8"     ,}, React.createElement('h3', { className: "font-bold text-red-800 mb-2"  ,}, "⚠️ 반드시 확인"  ), React.createElement('p', { className: "text-sm text-red-700" ,}, "작성 내용은 자동 저장되지 않습니다. 새로고침 시 모든 내용이 삭제됩니다. 마지막 페이지에서 반드시 워드 파일(.doc)로 다운로드하세요."               ))
    , React.createElement('div', { className: "bg-white rounded-lg shadow-lg p-6 mb-8"    ,}, React.createElement('div', { className: "pt-4 border-t border-gray-200"  ,}, React.createElement('p', { className: "text-xs text-gray-800 text-center"  ,}, "© 2026 CareerEngineer All Rights Reserved."     ), React.createElement('p', { className: "text-xs text-red-800 text-center mt-1 font-semibold"    ,}, "이 워크북은 저작권법에 의해 보호받는 저작물입니다. 무단 복제·배포·전송을 금합니다."        )))
    , React.createElement('button', { onClick: () => setShowIntro(false), className: "w-full py-4 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-lg hover:from-blue-700 hover:to-indigo-700 font-bold text-lg"          ,}, "1라운드 시작하기 →"  )
  ))));

  // ── 평가 ───────────────────────────────────────────────────
  if (currentPhase === 'evaluation') return (React.createElement('div', { className: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-4"    ,}, React.createElement('div', { className: "max-w-4xl mx-auto" ,}, React.createElement('div', { className: "bg-white rounded-lg shadow-lg p-8"   ,}
    , React.createElement('h2', { className: "text-3xl font-bold text-gray-800 mb-4 text-center"    ,}, "1라운드 완료! 🎉"  )
    , React.createElement('p', { className: "text-center text-gray-600 mb-4"  ,}, "부족한 Q를 선택하여 2라운드에서 심화 질문에 답변하세요"      )
    , React.createElement('div', { className: "bg-amber-50 border-l-4 border-amber-400 p-4 mb-6 text-sm text-amber-900 rounded"       ,}, React.createElement('p', { className: "font-semibold mb-1" ,}, "💡 선택 기준"  ), React.createElement('p', null, "면접관이 " , React.createElement('strong', null, "\"더 구체적으로?\"" ), "라고 물을 것 같은 Q를 선택하세요."     ), React.createElement('p', { className: "mt-1 text-amber-700" ,}, "3초 자가진단 통과가 어려웠던 질문을 우선 선택하세요."      ))
    , React.createElement('div', { className: "space-y-4 mb-8" ,}, round1Steps.slice(1).map(step => { const sid = step.id, sel = selectedSteps.includes(sid); return (React.createElement('div', { key: sid, className: `border-2 rounded-lg p-5 transition-all ${sel ? 'border-indigo-500 bg-indigo-50' : 'border-gray-200 hover:border-indigo-300'}`,}, React.createElement('div', { className: "flex items-start justify-between"  ,}, React.createElement('div', { className: "flex-1",}, React.createElement('h3', { className: "font-bold text-gray-800 mb-1"  ,}, step.title), React.createElement('p', { className: "text-sm text-gray-600 mb-2"  ,}, step.subtitle), React.createElement('div', { className: "bg-gray-50 rounded p-3 text-sm text-gray-700"    ,}, React.createElement('strong', null, "내 답변:" ), " " , _optionalChain([answers, 'access', _ => _[step.questions[0].id], 'optionalAccess', _2 => _2.substring, 'call', _3 => _3(0, 100)]) || '(답변 없음)', _optionalChain([answers, 'access', _4 => _4[step.questions[0].id], 'optionalAccess', _5 => _5.length]) > 100 && '...')), React.createElement('button', { onClick: () => toggleStepSelection(sid), className: `ml-4 px-4 py-2 rounded-lg font-semibold ${sel ? 'bg-indigo-600 text-white' : 'bg-gray-200 text-gray-700 hover:bg-gray-300'}`,}, sel ? '✓ 선택됨' : '심화 선택')))); }))
    , React.createElement('div', { className: "flex gap-4" ,}, React.createElement('button', { onClick: goToPrevStep, className: "flex items-center gap-2 px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 font-medium"         ,}, React.createElement(ChevronLeft, { className: "w-5 h-5" ,} ), " 이전" ), React.createElement('button', { onClick: goToNextStep, disabled: !canGoNext(), className: "flex-1 py-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 font-semibold text-lg"        ,}, "2라운드 시작 ("  , selectedSteps.length, "개 선택)" ))
  ), React.createElement('div', { className: "text-center mt-6" ,}, React.createElement('p', { className: "text-xs text-gray-500" ,}, "© 2026 CareerEngineer All Rights Reserved."     )))));

  // ── 완성 ───────────────────────────────────────────────────
  if (currentPhase === 'completed') return (React.createElement('div', { className: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-4"    ,}, React.createElement('div', { className: "max-w-4xl mx-auto" ,}, React.createElement('div', { className: "bg-white rounded-lg shadow-lg p-8"   ,}
    , React.createElement('div', { className: "text-center mb-8" ,}, React.createElement('div', { className: "inline-flex items-center justify-center w-20 h-20 bg-green-100 rounded-full mb-4"       ,}, React.createElement(Check, { className: "w-10 h-10 text-green-600"  ,} )), React.createElement('h2', { className: "text-3xl font-bold text-gray-800 mb-2"   ,}, "지원동기 완성! 🎉"  ), React.createElement('p', { className: "text-gray-600",}, "아래 내용을 확인하고 자유롭게 수정하세요"    ))
    , React.createElement('div', { className: "bg-red-100 border-2 border-red-500 rounded-lg p-5 mb-6"     ,}, React.createElement('div', { className: "flex items-start gap-3"  ,}, React.createElement('span', { className: "text-3xl",}, "⚠️"), React.createElement('div', null, React.createElement('p', { className: "text-base font-bold text-red-900 mb-2"   ,}, "반드시 다운로드하세요!" ), React.createElement('p', { className: "text-sm text-red-800" ,}, "새로고침하면 " , React.createElement('strong', null, "모든 내용이 삭제"  ), "됩니다. " , React.createElement('strong', null, "\"워드 파일로 다운로드\""  ), " 버튼을 눌러 저장하세요!"   ))))
    , React.createElement('div', { className: "bg-gradient-to-r from-blue-50 to-indigo-50 border-2 border-blue-200 rounded-lg p-5 mb-6"       ,}
      , React.createElement('div', { className: "flex items-center justify-between mb-3"   ,}, React.createElement('h3', { className: "text-lg font-bold text-gray-800 flex items-center gap-2"     ,}, React.createElement(Edit3, { className: "w-5 h-5 text-blue-600"  ,} ), " 완성된 지원동기 (수정 가능)"    ), React.createElement('button', { onClick: () => setShowRawAnswers(!showRawAnswers), className: "text-sm text-gray-600 hover:text-gray-800 flex items-center gap-1"     ,}, React.createElement(Eye, { className: "w-4 h-4" ,} ), showRawAnswers ? '원본 숨기기' : '원본 보기'))
      /* 활용 가이드 */
      , React.createElement('div', { className: "bg-purple-50 border border-purple-200 rounded-lg p-4 mb-4"     ,}
        , React.createElement('p', { className: "text-sm font-bold text-purple-900 mb-3"   ,}, "📋 내 답변 활용 가이드 — Q별 재료"       ), React.createElement('p', { className: "text-xs text-purple-700 mb-4"  ,}, "3라운드 연결 답변을 우선 사용. 없으면 아래 Q 답변에서 핵심만 골라 연결하세요."           )
        , React.createElement('div', { className: "bg-white border-l-4 border-purple-500 rounded p-3 mb-3"     ,}, React.createElement('p', { className: "text-xs font-bold text-purple-700 mb-2"   ,}, "도입부 — 왜 이 직무 + 왜 이 회사 (Q1·Q2)"         )
          , answers.connect_q1q2 && React.createElement('div', { className: "bg-purple-50 rounded p-2 mb-2"   ,}, React.createElement('p', { className: "text-xs text-purple-600 font-semibold"  ,}, "✅ 연결 Q1→Q2 (권장)"   ), React.createElement('p', { className: "text-xs text-gray-700 mt-1"  ,}, answers.connect_q1q2.substring(0,150), answers.connect_q1q2.length>150?'...':''))
          , answers.q1_1 && React.createElement('div', { className: "bg-gray-50 rounded p-2 mb-1"   ,}, React.createElement('p', { className: "text-xs text-gray-500 font-semibold"  ,}, "관심 계기 (Q1-1)"  ), React.createElement('p', { className: "text-xs text-gray-700 mt-1"  ,}, answers.q1_1.substring(0,100), answers.q1_1.length>100?'...':''))
          , React.createElement('p', { className: "text-xs text-purple-600 mt-2 italic"   ,}, "연결 예시: \"이 직무를 할 수 있는 곳은 많지만, 귀사를 선택한 이유는...\""           ))
        , React.createElement('div', { className: "bg-white border-l-4 border-pink-500 rounded p-3 mb-3"     ,}, React.createElement('p', { className: "text-xs font-bold text-pink-700 mb-2"   ,}, "중반부 — 무엇을 왜 준비 (Q3)"     )
          , answers.connect_q2q3 && React.createElement('div', { className: "bg-pink-50 rounded p-2 mb-2"   ,}, React.createElement('p', { className: "text-xs text-pink-600 font-semibold"  ,}, "✅ 연결 Q2→Q3 (권장)"   ), React.createElement('p', { className: "text-xs text-gray-700 mt-1"  ,}, answers.connect_q2q3.substring(0,150), answers.connect_q2q3.length>150?'...':''))
          , answers.q3_2 && React.createElement('div', { className: "bg-gray-50 rounded p-2 mb-1"   ,}, React.createElement('p', { className: "text-xs text-gray-500 font-semibold"  ,}, "준비 과정 (Q3-2)"  ), React.createElement('p', { className: "text-xs text-gray-700 mt-1"  ,}, answers.q3_2.substring(0,100), answers.q3_2.length>100?'...':''))
          , React.createElement('p', { className: "text-xs text-pink-600 mt-2 italic"   ,}, "연결 예시: \"그 확신이 생긴 이후 본격적으로 준비를 시작했습니다...\""        ))
        , React.createElement('div', { className: "bg-white border-l-4 border-purple-500 rounded p-3 mb-2"     ,}, React.createElement('p', { className: "text-xs font-bold text-purple-700 mb-2"   ,}, "마무리 — 어떻게 기여 (Q4)"    )
          , answers.connect_q3q4 && React.createElement('div', { className: "bg-purple-50 rounded p-2 mb-2"   ,}, React.createElement('p', { className: "text-xs text-purple-600 font-semibold"  ,}, "✅ 연결 Q3→Q4 (권장)"   ), React.createElement('p', { className: "text-xs text-gray-700 mt-1"  ,}, answers.connect_q3q4.substring(0,150), answers.connect_q3q4.length>150?'...':''))
          , answers.q4_1 && React.createElement('div', { className: "bg-gray-50 rounded p-2 mb-1"   ,}, React.createElement('p', { className: "text-xs text-gray-500 font-semibold"  ,}, "동기→역량→기여 (Q4-1)" ), React.createElement('p', { className: "text-xs text-gray-700 mt-1"  ,}, answers.q4_1.substring(0,100), answers.q4_1.length>100?'...':''))
          , React.createElement('p', { className: "text-xs text-purple-600 mt-2 italic"   ,}, "연결 예시: \"이렇게 준비해온 역량이 귀사에서 이런 방식으로...\""       ))
      )
      /* 체크리스트 */
      , React.createElement('div', { className: "bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4"     ,}, React.createElement('p', { className: "text-sm font-bold text-blue-900 mb-3"   ,}, "✅ 수정 전 최종 확인"    ), React.createElement('div', { className: "space-y-3",}
        , React.createElement('div', { className: "bg-white rounded p-3 border border-blue-100"    ,}, React.createElement('p', { className: "text-xs font-semibold text-blue-800 mb-1"   ,}, "① Q1: 관심 계기가 구체적 장면+감정이고, 가치관과 연결되는가?"       ), React.createElement('p', { className: "text-xs text-gray-500" ,}, "통과 못 하면 → "    , React.createElement('span', { className: "text-purple-600 font-semibold" ,}, "Q1-1, Q1-2" ), "로"))
        , React.createElement('div', { className: "bg-white rounded p-3 border border-blue-100"    ,}, React.createElement('p', { className: "text-xs font-semibold text-blue-800 mb-1"   ,}, "② Q2: 리서치 없이는 쓸 수 없는 이 회사만의 이유가 있는가?"          ), React.createElement('p', { className: "text-xs text-gray-500" ,}, "통과 못 하면 → "    , React.createElement('span', { className: "text-purple-600 font-semibold" ,}, "Q2-1(차별점)")))
        , React.createElement('div', { className: "bg-white rounded p-3 border border-blue-100"    ,}, React.createElement('p', { className: "text-xs font-semibold text-blue-800 mb-1"   ,}, "③ Q3: 역량 준비의 이유(\"~하기 위해\")가 명시되어 있는가?"       ), React.createElement('p', { className: "text-xs text-gray-500" ,}, "통과 못 하면 → "    , React.createElement('span', { className: "text-pink-600 font-semibold" ,}, "Q3-1, Q3-2" )))
        , React.createElement('div', { className: "bg-white rounded p-3 border border-blue-100"    ,}, React.createElement('p', { className: "text-xs font-semibold text-blue-800 mb-1"   ,}, "④ Q4: \"열심히 하겠다\"가 아닌 동기+역량의 인과적 결론인가?"       ), React.createElement('p', { className: "text-xs text-gray-500" ,}, "통과 못 하면 → "    , React.createElement('span', { className: "text-pink-600 font-semibold" ,}, "Q4-1 인과 연결"  )))
      ))
      , React.createElement('textarea', { value: finalText, onChange: e => setFinalText(e.target.value), rows: 20, className: "w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 resize-none font-serif leading-relaxed"          ,} )
    )
    , showRawAnswers && React.createElement('div', { className: "bg-gray-50 border border-gray-200 rounded-lg p-4 mb-6"     ,}, React.createElement('h4', { className: "font-semibold text-gray-800 mb-3"  ,}, "📋 원본 답변 참고"   ), React.createElement('pre', { className: "text-sm text-gray-700 whitespace-pre-wrap font-sans"   ,}, getRawText()))
    , React.createElement('button', { onClick: downloadFinalText, className: "w-full flex items-center justify-center gap-2 px-6 py-4 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-lg hover:from-blue-700 hover:to-indigo-700 font-semibold text-lg shadow-lg mb-4"                 ,}, React.createElement(Download, { className: "w-6 h-6" ,} ), " 워드 파일로 다운로드 (.doc)"    )
    , downloadSuccess && React.createElement('div', { className: "bg-green-100 border-2 border-green-500 rounded-lg p-4 text-center mb-4"      ,}, React.createElement('p', { className: "text-green-800 font-semibold" ,}, "✅ 다운로드 완료!"  ))
    , React.createElement('div', { className: "bg-blue-50 border border-blue-200 rounded-lg p-4 text-center"     ,}, React.createElement('p', { className: "text-sm text-blue-800" ,}, "💾 " , React.createElement('strong', null, "워드에서 편집 가능:"  ), " .doc 파일을 Word에서 열어 자유롭게 편집하세요."      ))
    , React.createElement('div', { className: "flex gap-4 mt-4"  ,}, React.createElement('button', { onClick: goToPrevStep, className: "flex items-center gap-2 px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 font-medium"         ,}, React.createElement(ChevronLeft, { className: "w-5 h-5" ,} ), " 이전으로" ))
  ), React.createElement('div', { className: "bg-white rounded-lg shadow-lg p-6 mt-6"    ,}, React.createElement('div', { className: "pt-4 border-t border-gray-200"  ,}, React.createElement('p', { className: "text-xs text-gray-800 text-center"  ,}, "© 2026 CareerEngineer All Rights Reserved."     ), React.createElement('p', { className: "text-xs text-red-800 text-center mt-1 font-semibold"    ,}, "이 워크북은 저작권법에 의해 보호받는 저작물입니다. 무단 복제·배포·전송을 금합니다."        ))))));

  // ── 메인 질문 ──────────────────────────────────────────────
  const sd = currentPhase === 'round1' ? round1Steps[currentStep] : currentPhase === 'round2' ? { title: `${round1Steps[selectedSteps[currentStep]].title} - 심화`, questions: round2Questions[selectedSteps[currentStep]] } : { title: '3라운드: 연결 및 완성', questions: [round3Questions[currentStep]] };

  return (React.createElement('div', { className: "min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-4"    ,}, React.createElement('div', { className: "max-w-4xl mx-auto" ,}
    , React.createElement('div', { className: "bg-white rounded-lg shadow-lg p-6 mb-6"    ,}, React.createElement('h1', { className: "text-3xl font-bold text-gray-800 mb-2"   ,}, "CareerEngineer 지원동기 작성 워크북"   ), React.createElement('p', { className: "text-gray-600",}, "체계적인 3라운드 시스템으로 완성하는 지원동기"    ), React.createElement('div', { className: "mt-4",}, React.createElement('div', { className: "flex justify-between text-sm text-gray-600 mb-2"    ,}, React.createElement('span', null, currentPhase === 'round1' ? '1라운드' : currentPhase === 'round2' ? '2라운드' : '3라운드', " - "  , sd.title), React.createElement('span', null, "진행률: " , Math.round(progress), "%")), React.createElement('div', { className: "w-full bg-gray-200 rounded-full h-3"   ,}, React.createElement('div', { className: "bg-gradient-to-r from-blue-500 to-indigo-600 h-3 rounded-full transition-all duration-500"      , style: { width: progress + '%' },} ))))
    , React.createElement('div', { className: "bg-white rounded-lg shadow-lg p-8"   ,}
      , React.createElement('h2', { className: "text-2xl font-bold text-gray-800 mb-2"   ,}, sd.title), sd.subtitle && React.createElement('p', { className: "text-gray-600 mb-6" ,}, sd.subtitle)
      , currentStep === 0 && currentPhase === 'round1' ? (
        React.createElement('div', { className: "space-y-4",}, [['industry','지원하고자 하는 산업','예: IT, 금융, 제조 등'],['position','지원하고자 하는 직무','예: 마케팅, 개발, 기획 등'],['company','지원하고자 하는 회사명','예: 삼성전자, 네이버 등']].map(([f,l,p]) => (React.createElement('div', { key: f,}, React.createElement('label', { className: "block text-sm font-semibold text-gray-700 mb-2"    ,}, l), React.createElement('input', { type: "text", value: (basicInfo )[f], onChange: e => handleBasicInfoChange(f, e.target.value), className: "w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"       , placeholder: p,} )))))
      ) : (
        React.createElement('div', { className: "space-y-6",}, (sd.questions ).map((q) => (React.createElement('div', { key: q.id, className: "mb-6 border-b border-gray-200 pb-6 last:border-b-0"    ,}
          , React.createElement('div', { className: "flex items-start justify-between mb-2"   ,}, React.createElement('label', { className: "text-lg font-semibold text-gray-800"  ,}, q.label), q.guide && React.createElement('button', { onClick: () => toggleGuide(q.id), className: "flex items-center gap-1 text-sm text-blue-600 hover:text-blue-800"     ,}, React.createElement(HelpCircle, { className: "w-4 h-4" ,} ), showGuide[q.id] ? '가이드 숨기기' : '가이드 보기'))
          , q.hint && React.createElement('p', { className: "text-sm text-gray-600 mb-2"  ,}, "💡 " , q.hint)
          , q.referenceQuestions && React.createElement('div', { className: "bg-indigo-50 border-l-4 border-indigo-400 p-4 mb-3"    ,}, React.createElement('p', { className: "text-sm font-semibold text-indigo-900 mb-2"   ,}, "📚 참고: 이전 답변"   ), React.createElement('div', { className: "space-y-3",}, q.referenceQuestions.map((rid) => { const rq = round1Steps.flatMap(s => s.questions || []).find(x => _optionalChain([x, 'optionalAccess', _6 => _6.id]) === rid); if (!rq || !answers[rid]) return null; return React.createElement('div', { key: rid, className: "bg-white p-3 rounded text-sm"   ,}, React.createElement('p', { className: "font-semibold text-gray-700 mb-1"  ,}, rq.label), React.createElement('p', { className: "text-gray-600 italic" ,}, _optionalChain([answers, 'access', _7 => _7[rid], 'optionalAccess', _8 => _8.substring, 'call', _9 => _9(0,150)]), _optionalChain([answers, 'access', _10 => _10[rid], 'optionalAccess', _11 => _11.length])>150?'...':'')); })))
          , q.guide && showGuide[q.id] && React.createElement('div', { className: "bg-blue-50 border-l-4 border-blue-400 p-4 mb-3 space-y-3"     ,}, React.createElement('div', null, React.createElement('p', { className: "text-sm font-semibold text-blue-900 mb-1"   ,}, "📝 " , q.guide.description)), React.createElement('div', null, React.createElement('p', { className: "text-sm font-semibold text-blue-900 mb-1"   ,}, "🎯 " , q.guide.diagnosis)), q.guide.helpQuestions && React.createElement('div', null, React.createElement('p', { className: "text-sm font-semibold text-blue-900 mb-1"   ,}, "❓ 구체화 도움 질문:"   ), React.createElement('ul', { className: "text-sm text-blue-800 space-y-1 ml-4"   ,}, q.guide.helpQuestions.map((h, i) => React.createElement('li', { key: i,}, "• " , h)))), q.guide.ifDifficult && React.createElement('div', null, React.createElement('p', { className: "text-sm font-semibold text-blue-900 mb-1"   ,}, "💭 답변하기 어렵다면:"  ), React.createElement('p', { className: "text-sm text-blue-800" ,}, q.guide.ifDifficult)), q.guide.ifStillDifficult && React.createElement('div', null, React.createElement('p', { className: "text-sm font-semibold text-blue-900 mb-1"   ,}, "💡 그래도 어렵다면:"  ), React.createElement('p', { className: "text-sm text-blue-800" ,}, q.guide.ifStillDifficult)))
          , React.createElement('textarea', { value: answers[q.id] || '', onChange: e => handleAnswerChange(q.id, e.target.value), rows: q.rows || 3, className: "w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 resize-none"        , placeholder: q.placeholder,} )
        ))))
      )
      , React.createElement('div', { className: "flex gap-4 mt-8"  ,}, React.createElement('button', { onClick: goToPrevStep, className: "flex items-center gap-2 px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 font-medium"         ,}, React.createElement(ChevronLeft, { className: "w-5 h-5" ,} ), " 이전" ), React.createElement('button', { onClick: goToNextStep, disabled: !canGoNext(), className: "flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 font-semibold"            ,}, "다음 " , React.createElement(ChevronRight, { className: "w-5 h-5" ,} )))
    )
    , React.createElement('div', { className: "text-center mt-6" ,}, React.createElement('p', { className: "text-xs text-gray-500" ,}, "© 2026 CareerEngineer All Rights Reserved."     ))
  )));
};

export default MotivationWorkbook;
